# Generated by Django 4.1.7 on 2023-05-17 15:05
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='O2OPaymentLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user account id')),
                ('payment_id', models.BigIntegerField(db_index=True, verbose_name='o2opayment id')),
                ('category', models.SmallIntegerField(db_index=True, default=1, verbose_name='log category')),
                ('expire_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='expiration time')),
                ('usage_count', models.IntegerField(default=0, verbose_name='current usage count')),
                ('note', models.CharField(max_length=256, null=True, verbose_name='Notes on payment log')),
                ('order_id', models.BigIntegerField(db_index=True, null=True, verbose_name='buy order id')),
                ('record_id', models.BigIntegerField(db_index=True, null=True, verbose_name='consume record id')),
            ],
            options={
                'verbose_name': 'O2OPaymentLog',
                'verbose_name_plural': 'O2OPaymentLog',
                'db_table': 'asset_o2opayment_log',
            },
        ),
        migrations.CreateModel(
            name='O2OPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user account id')),
                ('transient_expire_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Transient expiration time')),
                ('transient_usage_count', models.IntegerField(default=0, verbose_name='Transient expiration usage count')),
                ('persistence_usage_count', models.IntegerField(default=0, verbose_name='Persistence expiration usage count')),
                ('free_expire_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='free expiration time')),
                ('free_usage_count', models.IntegerField(default=0, verbose_name='Free usage count')),
                ('is_enable', models.BooleanField(db_index=True, default=True, verbose_name='Whether it is available or not')),
            ],
            options={
                'verbose_name': 'O2OPayment',
                'verbose_name_plural': 'O2OPayment',
                'db_table': 'asset_o2opayment',
            },
        ),
        migrations.CreateModel(
            name='PointsLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user account id')),
                ('point_id', models.BigIntegerField(db_index=True, verbose_name='points foreignkey id')),
                ('category', models.SmallIntegerField(default=1, verbose_name='points change category')),
                ('amount', models.BigIntegerField(default=0, verbose_name='The number of points changed this time')),
                ('note', models.CharField(max_length=256, null=True, verbose_name='Notes on integral changes')),
            ],
            options={
                'verbose_name': 'PointsLog',
                'verbose_name_plural': 'PointsLog',
                'db_table': 'asset_points_log',
            },
        ),
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user account id')),
                ('total', models.BigIntegerField(default=0, verbose_name='total points')),
            ],
            options={
                'verbose_name': 'Points',
                'verbose_name_plural': 'Points',
                'db_table': 'asset_points',
            },
        ),
    ]
