# Generated by Django 4.1.7 on 2023-05-17 17:18
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsWithdrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user account id')),
                ('realname', models.CharField(max_length=64, verbose_name='The real name of the withdrawing person')),
                ('contact', models.CharField(max_length=256, verbose_name='Contact information')),
                ('point', models.BigIntegerField(default=0, verbose_name='The number of points changed this time')),
                ('amount', models.FloatField(default=0, verbose_name='The amount exchanged')),
                ('ratio', models.FloatField(default=0, verbose_name='Ratio of points to cash')),
                ('status', models.SmallIntegerField(db_index=True, default=0, verbose_name='withdraw status')),
                ('audit_user_id', models.BigIntegerField(db_index=True, verbose_name='withdraw auditor')),
                ('audit_time', models.DateTimeField(null=True, verbose_name='withdraw audit time')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='withdraw finish time')),
            ],
            options={
                'verbose_name': 'PointsWithdraw',
                'verbose_name_plural': 'PointsWithdraw',
                'db_table': 'asset_points_withdraw',
            },
        ),
    ]
