# Generated by Django 4.1.7 on 2023-05-19 14:20
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_pointswithdrawmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='expire_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True, verbose_name='expiration time'),
        ),
    ]
