# Generated by Django 4.1.7 on 2023-05-23 15:59
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_o2opaymentlogmodel_expire_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='o2opaymentlogmodel',
            options={'verbose_name': '资源消耗记录', 'verbose_name_plural': '资源消耗记录'},
        ),
        migrations.AlterModelOptions(
            name='o2opaymentmodel',
            options={'verbose_name': '资源', 'verbose_name_plural': '资源'},
        ),
        migrations.AlterModelOptions(
            name='pointslogmodel',
            options={'verbose_name': '积分记录', 'verbose_name_plural': '积分记录'},
        ),
        migrations.AlterModelOptions(
            name='pointsmodel',
            options={'verbose_name': '积分', 'verbose_name_plural': '积分'},
        ),
        migrations.AlterModelOptions(
            name='pointswithdrawmodel',
            options={'verbose_name': '积分提现', 'verbose_name_plural': '积分提现'},
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='category',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='钱包类型'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='expire_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='note',
            field=models.CharField(max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='order_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='购买订单id'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='payment_id',
            field=models.BigIntegerField(db_index=True, verbose_name='记录id'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='record_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='消耗记录id'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='使用数'),
        ),
        migrations.AlterField(
            model_name='o2opaymentlogmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='free_expire_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='免费过期时间'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='free_usage_count',
            field=models.IntegerField(default=0, verbose_name='免费次数'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='is_enable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='persistence_usage_count',
            field=models.IntegerField(default=0, verbose_name='永久使用次数'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='transient_expire_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='临时有限时间'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='transient_usage_count',
            field=models.IntegerField(default=0, verbose_name='临时使用次数'),
        ),
        migrations.AlterField(
            model_name='o2opaymentmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='pointslogmodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='变动积分数'),
        ),
        migrations.AlterField(
            model_name='pointslogmodel',
            name='category',
            field=models.SmallIntegerField(default=1, verbose_name='变动类别'),
        ),
        migrations.AlterField(
            model_name='pointslogmodel',
            name='note',
            field=models.CharField(max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='pointslogmodel',
            name='point_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='pointslogmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='pointsmodel',
            name='total',
            field=models.BigIntegerField(default=0, verbose_name='总积分数'),
        ),
        migrations.AlterField(
            model_name='pointsmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='amount',
            field=models.FloatField(default=0, verbose_name='兑换积分数'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='audit_time',
            field=models.DateTimeField(null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='audit_user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='contact',
            field=models.CharField(max_length=256, verbose_name='提现人信息'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='finish_time',
            field=models.DateTimeField(null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='point',
            field=models.BigIntegerField(default=0, verbose_name='变动积分数'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='ratio',
            field=models.FloatField(default=0, verbose_name='积分与现金的比率'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='realname',
            field=models.CharField(max_length=64, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='提现状态'),
        ),
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
    ]
