# Generated by Django 4.1.7 on 2023-05-25 15:17
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_o2opaymentlogmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointswithdrawmodel',
            name='openid',
            field=models.CharField(max_length=128, null=True, verbose_name='微信openid'),
        ),
    ]
