# Generated by Django 4.1.7 on 2023-05-25 19:30
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_pointswithdrawmodel_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='contact',
            field=models.CharField(max_length=256, null=True, verbose_name='提现人信息'),
        ),
    ]
