# Generated by Django 4.1.7 on 2023-05-25 19:33
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_pointswithdrawmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointswithdrawmodel',
            name='audit_user_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='审核人'),
        ),
    ]
