# Generated by Django 4.1.7 on 2023-05-29 17:38
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_pointswithdrawmodel_audit_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointslogmodel',
            name='source',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='积分来源'),
        ),
    ]
