# Generated by Django 4.1.7 on 2023-05-30 11:58
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_pointslogmodel_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointswithdrawmodel',
            name='transfer_note',
            field=models.TextField(null=True, verbose_name='Transfer note'),
        ),
    ]
