# Generated by Django 4.1.7 on 2023-02-28 03:26
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='db:chatrecord: user foreign key')),
                ('msg_type', models.SmallIntegerField(db_index=True, default=1, verbose_name='db:chatrecord: message type')),
                ('question', models.TextField(verbose_name='db:chatrecord: question')),
                ('answer', models.TextField(verbose_name='db:chatrecord: answer')),
                ('approval', models.IntegerField(default=0, verbose_name='db:chatrecord: approval number')),
                ('response', models.TextField(verbose_name='db:chatrecord: chatgpt response result')),
                ('success', models.BooleanField(default=False, verbose_name='db:chatrecord: QA success')),
                ('question_time', models.DateTimeField(verbose_name='db:chatrecord: question time')),
                ('response_time', models.DateTimeField(verbose_name='db:chatrecord: chatgpt response time')),
            ],
            options={
                'verbose_name': 'db:chatrecord:ChatRecord',
                'verbose_name_plural': 'db:chatrecord:ChatRecord',
                'db_table': 'chat_record',
            },
        ),
    ]
