# Generated by Django 4.1.7 on 2023-02-28 06:30
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='answer',
            field=models.TextField(null=True, verbose_name='db:chatrecord: answer'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='response',
            field=models.TextField(null=True, verbose_name='db:chatrecord: chatgpt response result'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='response_time',
            field=models.DateTimeField(null=True, verbose_name='db:chatrecord: chatgpt response time'),
        ),
    ]
