# Generated by Django 4.1.7 on 2023-03-02 06:35
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatrecordmodel_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatrecordmodel',
            options={'verbose_name': 'ChatRecord Table', 'verbose_name_plural': 'ChatRecord Table'},
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='approval',
            field=models.IntegerField(default=0, verbose_name='approval number'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='msg_type',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='chat message type'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='question_time',
            field=models.DateTimeField(verbose_name='question request time'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='response',
            field=models.TextField(null=True, verbose_name='chatgpt response result'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='response_time',
            field=models.DateTimeField(null=True, verbose_name='chatgpt response time'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='success',
            field=models.BooleanField(default=False, verbose_name='QA success status'),
        ),
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='chat user id'),
        ),
    ]
