# Generated by Django 4.1.7 on 2023-03-02 07:48
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatrecordmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecordmodel',
            name='prompt_tokens',
            field=models.IntegerField(default=0, verbose_name='question tokens usage'),
        ),
        migrations.AddField(
            model_name='chatrecordmodel',
            name='resp_tokens',
            field=models.IntegerField(default=0, verbose_name='resp tokens usage'),
        ),
        migrations.AddField(
            model_name='chatrecordmodel',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='total tokens usage'),
        ),
    ]
