# Generated by Django 4.1.7 on 2023-03-23 17:18
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatgptkeymodel_chatrecordmodel_chatgpt_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptkeymodel',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='enable'),
        ),
        migrations.AlterField(
            model_name='chatgptkeymodel',
            name='key',
            field=models.CharField(max_length=128, unique=True, verbose_name='chatgpt key'),
        ),
    ]
