# Generated by Django 4.1.7 on 2023-03-23 17:30
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatgptkeymodel_enable_alter_chatgptkeymodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecordmodel',
            name='chatgpt_key_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='chatgpt key foreign key'),
        ),
    ]
