# Generated by Django 4.1.7 on 2023-03-29 17:25
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatrecordmodel_chatgpt_key_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=128, verbose_name='chat topic')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user foreign key')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatrecordmodel',
            name='chat_topic_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='chat topic id'),
        ),
    ]
