# Generated by Django 4.1.7 on 2023-05-30 18:32
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatgptkeymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattopicmodel',
            name='success',
            field=models.BooleanField(default=False, verbose_name='话题是否生成成功'),
        ),
    ]
