# Generated by Django 4.1.7 on 2023-06-02 12:18
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chattopicmodel_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptkeymodel',
            name='reason',
            field=models.CharField(max_length=256, null=True, verbose_name='disable reason'),
        ),
    ]
