# Generated by Django 4.1.7 on 2023-02-28 06:16
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogmodel',
            name='response',
            field=models.TextField(null=True, verbose_name='db:MessageLog: send message response'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='response_time',
            field=models.DateTimeField(null=True, verbose_name='db:MessageLog: response time'),
        ),
    ]
