# Generated by Django 4.1.7 on 2023-03-03 05:42
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_walletmodel_alter_accountmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user id')),
                ('score_id', models.BigIntegerField(db_index=True, verbose_name='score foreign key')),
                ('category', models.SmallIntegerField(default=1, verbose_name='score operate category')),
                ('amount', models.BigIntegerField(default=0, verbose_name='score')),
                ('txid', models.CharField(max_length=128, null=True, verbose_name='chain transaction id')),
                ('result', models.TextField(null=True, verbose_name='chain response')),
            ],
            options={
                'verbose_name': 'ScoreLog',
                'verbose_name_plural': 'ScoreLog',
                'db_table': 'account_score_log',
            },
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user id')),
                ('balance', models.BigIntegerField(default=0, verbose_name='score balance')),
                ('chain', models.CharField(db_index=True, max_length=32, verbose_name='belong to the chain')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'score',
                'db_table': 'account_score',
            },
        ),
        migrations.RemoveField(
            model_name='walletmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='chain',
            field=models.CharField(db_index=True, default=None, max_length=32, verbose_name='belong to the chain'),
            preserve_default=False,
        ),
    ]
