# Generated by Django 4.1.7 on 2023-03-03 07:17
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_scorelogmodel_scoremodel_remove_walletmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremodel',
            name='chain',
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='balance'),
        ),
    ]
