# Generated by Django 4.1.7 on 2023-03-23 15:45
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_scoremodel_chain_walletmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='user_type',
            field=models.SmallIntegerField(default=1, verbose_name='user type'),
        ),
    ]
