# Generated by Django 4.1.7 on 2023-04-07 16:25
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accountmodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='user id')),
                ('invited_user_id', models.BigIntegerField(db_index=True, verbose_name='Invited person')),
                ('experience', models.IntegerField(default=1, verbose_name='user experience times')),
                ('expired_time', models.DateField(db_index=True, verbose_name='invitation expiration time')),
            ],
            options={
                'verbose_name': 'InviteLogs',
                'verbose_name_plural': 'InviteLogs',
                'db_table': 'invite_log',
            },
        ),
    ]
