# Generated by Django 4.1.7 on 2023-05-16 17:26
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invitelogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitelogmodel',
            new_name='inviter_user_id',
            old_name='user_id',
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='inviter_user_id',
            field=models.BigIntegerField(db_index=True, default=None, verbose_name='inviter user account id'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='invitelogmodel',
            new_name='user_id',
            old_name='invited_user_id',
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, default=None, verbose_name='user account id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitelogmodel',
            name='super_inviter_user_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='super inviter user account id'),
        )
    ]
