# Generated by Django 4.1.7 on 2023-05-17 10:25
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_invitelogmodel_invited_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='config item name')),
                ('value', models.CharField(blank=True, max_length=256, null=True, verbose_name='config item value')),
                ('value_type', models.CharField(default='string', max_length=32, verbose_name='config item value type')),
                ('description', models.TextField(verbose_name='config item description')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
                'db_table': 'config',
            },
        ),
    ]
