# Generated by Django 4.1.7 on 2023-05-23 15:59
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_scorelogmodel_samascorelogmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.AlterModelOptions(
            name='configmodel',
            options={'verbose_name': '配置表', 'verbose_name_plural': '配置表'},
        ),
        migrations.AlterModelOptions(
            name='invitelogmodel',
            options={'verbose_name': '邀请记录表', 'verbose_name_plural': '邀请记录表'},
        ),
        migrations.AlterModelOptions(
            name='messagelogmodel',
            options={'verbose_name': '短信记录', 'verbose_name_plural': '短信记录'},
        ),
        migrations.AlterModelOptions(
            name='samascorelogmodel',
            options={'verbose_name': '积分日志', 'verbose_name_plural': '积分日志'},
        ),
        migrations.AlterModelOptions(
            name='samawalletmodel',
            options={'verbose_name': '钱包', 'verbose_name_plural': '钱包'},
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='_password_hash',
            field=models.CharField(max_length=512, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='avatar',
            field=models.CharField(max_length=128, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='experience',
            field=models.SmallIntegerField(default=10, verbose_name='体验次数'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否vip'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='login_ip',
            field=models.CharField(max_length=32, null=True, verbose_name='最近登录ip'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='login_time',
            field=models.DateTimeField(null=True, verbose_name='最近登录时间'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='mobile',
            field=models.CharField(max_length=16, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='user_type',
            field=models.SmallIntegerField(default=1, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='description',
            field=models.TextField(verbose_name='配置项描述'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='配置项名称'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='配置项值'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='value_type',
            field=models.CharField(default='string', max_length=32, verbose_name='配置项的值'),
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='体验次数'),
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='expired_time',
            field=models.DateField(db_index=True, verbose_name='邀请过期时间'),
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='inviter_user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='super_inviter_user_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='invitelogmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='category',
            field=models.SmallIntegerField(default=0, verbose_name='短信类型'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='content',
            field=models.TextField(verbose_name='短信内容'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='mobile',
            field=models.CharField(db_index=True, max_length=16, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='request_time',
            field=models.DateTimeField(verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='response',
            field=models.TextField(null=True, verbose_name='响应内容'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='response_time',
            field=models.DateTimeField(null=True, verbose_name='响应时间'),
        ),
        migrations.AlterField(
            model_name='messagelogmodel',
            name='success',
            field=models.BooleanField(default=False, verbose_name='短信发送状态'),
        ),
        migrations.AlterField(
            model_name='samascorelogmodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='samascorelogmodel',
            name='category',
            field=models.SmallIntegerField(default=1, verbose_name='积分操作类别'),
        ),
        migrations.AlterField(
            model_name='samascorelogmodel',
            name='result',
            field=models.TextField(null=True, verbose_name='链响应结果'),
        ),
        migrations.AlterField(
            model_name='samascorelogmodel',
            name='score_id',
            field=models.BigIntegerField(db_index=True, verbose_name='积分外键id'),
        ),
        migrations.AlterField(
            model_name='samascorelogmodel',
            name='txid',
            field=models.CharField(max_length=128, null=True, verbose_name='链交易id'),
        ),
        migrations.AlterField(
            model_name='samascorelogmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='samascoremodel',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='积分余额'),
        ),
        migrations.AlterField(
            model_name='samascoremodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='samawalletmodel',
            name='address',
            field=models.CharField(db_index=True, max_length=64, verbose_name='钱包地址'),
        ),
        migrations.AlterField(
            model_name='samawalletmodel',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='samawalletmodel',
            name='chain',
            field=models.CharField(db_index=True, max_length=32, verbose_name='所属链'),
        ),
        migrations.AlterField(
            model_name='samawalletmodel',
            name='private_key',
            field=models.CharField(max_length=512, verbose_name='钱包私钥'),
        ),
        migrations.AlterField(
            model_name='samawalletmodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
    ]
