# Generated by Django 4.1.7 on 2023-05-25 14:25
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_accountmodel_options_alter_configmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='openid',
            field=models.CharField(max_length=128, null=True, verbose_name='微信openid'),
        ),
    ]
