# Generated by Django 4.1.7 on 2023-05-30 17:09
# flake8: noqa
# pylint: skip-file
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_accountmodel_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='create_time')),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified_time')),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='用户id')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='feedback title')),
                ('content', models.TextField(null=True, verbose_name='feedback conennt')),
                ('status', models.SmallIntegerField(db_index=True, default=1, verbose_name='提现状态')),
                ('reply', models.TextField(null=True, verbose_name='feedback reply')),
                ('reply_user_id', models.BigIntegerField(null=True, verbose_name='reply user id')),
                ('reply_time', models.DateTimeField(null=True, verbose_name='reply time')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback',
            },
        ),
    ]
