# Generated by Django 4.1.7 on 2023-05-30 17:15
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='reply_time',
            field=models.DateTimeField(null=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='reply_user_id',
            field=models.BigIntegerField(null=True, verbose_name='回复用户id'),
        ),
    ]
