# Generated by Django 4.1.7 on 2023-05-30 18:32
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_feedbackmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samascoremodel',
            options={'verbose_name': 'Sama积分', 'verbose_name_plural': 'Sama积分'},
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='content',
            field=models.TextField(null=True, verbose_name='反馈内容'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='reply',
            field=models.TextField(null=True, verbose_name='反馈回复内容'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='反馈标题'),
        ),
    ]
