# Generated by Django 4.1.7 on 2023-07-07 17:22
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_samascoremodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='email',
            field=models.CharField(max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
