# Generated by Django 4.1.7 on 2023-05-18 17:47
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_time',
            field=models.DateTimeField(null=True, verbose_name='order payment time'),
        ),
    ]
