# Generated by Django 4.1.7 on 2023-05-23 15:59
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermodel_payment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_number',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='out_trade_no',
            field=models.CharField(db_index=True, default=None, max_length=32, verbose_name='out_trade_no name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='transaction_id'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付金额'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='package_id',
            field=models.BigIntegerField(db_index=True, verbose_name='套餐id'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.SmallIntegerField(default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_time',
            field=models.DateTimeField(null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status_note',
            field=models.CharField(max_length=64, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='orderpackagemodel',
            name='category',
            field=models.SmallIntegerField(default=0, verbose_name='套餐类别'),
        ),
        migrations.AlterField(
            model_name='orderpackagemodel',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='套餐名称'),
        ),
        migrations.AlterField(
            model_name='orderpackagemodel',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='套餐单价'),
        ),
        migrations.AlterField(
            model_name='orderpackagemodel',
            name='priority',
            field=models.IntegerField(db_index=True, default=1, verbose_name='套餐排序优先级'),
        ),
        migrations.AlterField(
            model_name='orderpackagemodel',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='套餐可使用次数'),
        ),
        migrations.AlterField(
            model_name='orderpackagemodel',
            name='usage_days',
            field=models.SmallIntegerField(default=0, verbose_name='套餐可使用天数'),
        ),
    ]
