# Generated by Django 4.1.7 on 2023-05-24 17:47
# flake8: noqa
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_ordermodel_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='client',
            field=models.CharField(default='native', max_length=16, verbose_name='支付客户端'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='out_trade_no',
            field=models.CharField(db_index=True, max_length=32, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='微信支付订单号'),
        ),
    ]
